### ISSUE TITLE
Artikel mit Varianten wird nicht geupdatet

### ISSUE THREAD

**Issue by thescrat** [nahati/contao-isotope-stock#7]
Hi, 

ich habe aktuell folgende Konstellation. Ich baue gerade einen Ticket-Shop. Dort gibt es einen Artikel "Tickets" (Vaterartikel) mit 2 Varianten (Ticket kaufen, Ticket reservieren).
Insgesamt gibt es jedoch nur n-Tickets, die ich logischerweise dem Vaterartikel zuweise. Bestellt werden jedoch die Varianten (Kinderartikel). Wie das Verhältnis zwischen Variante 1 & Variante 2 ist, weiß ich natürlich nicht, irgendwann sind halt die n-Tickets aufgebraucht.

Leider verringert sich die Anzahl nach einer Bestellung nicht beim Vaterartikel (dessen Anzahl ich im Frontend anzeige)

Weise ich den Varianten über das Attribut die 'quantity' zu, sehe ich dort den verringerten Wert. Müsste daher nicht geprüft werden ob eine Variante überhaupt das Attribut zugweisen bekommen hat und im nächsten Schritt den Vater prüfen?

Update: Ich denke ich habe den "Fehler" gefunden.
https://github.com/nahati/contao-isotope-stock/blob/4e2ca059ae3dd6d6447b99fbed4716b050310943/src/EventListener/PostCheckoutListener.php#L74

Genau an dieser Stelle wird der geminderte Wert geupdatet. Allerdings liefert $objProduct->getId() die ID der Variante. $objProduct->pid würde hier (für meinen Fall) das korrekte Ergebnis erziehlen. Evtl. sollte man hier per $objProduct->isVariant() prüfen ob es sich um eine Variante handelt und ob diese überhaupt 'quantity' per Attribut hat, ansonsten das Update auf $objProduct->pid machen. 

Könntet ihr das bitte einmal prüfen? 
Vielen Dank

**Comment by Ernestopheles** [comment]
Danke dass du die extension benutzst und den Hinweis.

Bisher ist der Fall _Produkt hat Varianten_ nicht enthalten. Rüste ich gerne nach, dein Vorschlag scheint mir gut zu passen.

**Comment by Ernestopheles** [comment]
Ich muss dich leider um etwas Geduld bitten. Habe eine Lösung ausgearbeitet, möchte die aber nicht ohne PHPUnit-Tests veröffentlichen. Hier hänge ich jedoch in der Luft, da einige meiner Tests zur Zeit noch nicht lauffähig sind und mir da sowohl eine fundierte Dokumentation als auch Unterstützung fehlt. Wenn man auf sich alleine gestellt ist, kann man bestimmte Hürden nur schlecht überwinden.

**Comment by Ernestopheles** [comment]
See https://github.com/contao/test-case/issues/17

Any Help welcome as Community is ignoring my questions

**Comment by Ernestopheles** [comment]
I do not think Contao Community is helpful for me at all. Too often got ungood reactions; too seldom real help. Documentation often not sufficient enough, without some support its a mess to create s.th. new.

Thats why I am not going to go on expanding this extension to variants. Had been almost finished but lost motivation.

**Comment by thescrat** [comment]
Warum hast du denn die Sprache gewechselt? Hast du die Vermutung, dass es hier international wird, wenn dir schon niemand aus der Community beim Unit-Test behilflich sein möchte?

Erstmal trotzdem vielen Dank für dein Engagement. Und ich kann absolut verstehen, dass man die Motivation verliert, wenn man bei Fehlern keine Hilfe von der Community bekommt. Kenne ich leider seit Jahren.
Allerdings finde ich es etwas komisch, dass du dich da so sehr auf die Unit-Tests versteifst. Die haben mit Sicherheit ihre Berechtigungen, aber das Grundlegende Problem ist doch eher ein logisches. Es gibt je Artikel doch nur 3 Möglichkeiten

- Einzelartikel (mit Bestand)
- Vaterartikel (mit Bestand) mit Varianten (ohne Einzelbestand)
- Vaterartikel (ohne Bestand) mit Varianten (mit Einzelbestand)

Und das muss eigentlich geprüft werden. Wofür brauchst du dafür einen Unit-Test?

Ich schau mal ob ich die Tage Zeit finde mir das anzusehen und dir nen Commit zu schicken, welches die Varianten integriert. Meine Lösung funktioniert aktuell (hardcoded) sehr gut, aber beim nächsten Update etc. ist halt kaputt.

**Comment by Ernestopheles** [comment]
> Warum hast du denn die Sprache gewechselt?

Englisch ist eigentlich üblich und sinnig

Ich habe wie gesagt eine fast fertige Lösung, die ich noch sauber mit Unit Tests testen möchte bevor ich sie veröffentliche. Das ist einfach mein Anspruch an Qualität, dass saubere Tests da sind. Vielleicht mach ich doch irgendwann weiter, wenn mein Frust sich gelegt hat und ich robust genug bin, die - sicherlich kommenden - neuen Herausforderungen ohne wirkliche Unterstützung zu meistern. Momentan fühle ich mich eben alleine gelassen in meinem Engagement (ich selber brauche die Variantenlösung nicht) und es wird ja immer so sehr betont, was jede/r einzelne Tolles für Contao tut und zahlt, jetzt wird sogar ein separater support Kanal eingerichtet für die die zahlen können. Ich habe meine Contao association Mitgliedschaft deshalb jetzt gekündigt.

Also immer wieder mangels Unterstützung hängen bleiben in der Arbeit, die ansonsten viel Spaß macht, ich aber den Spaß verliere wenn ich tagelang herumprobieren muss oder die Lösung gar nicht finde. ChatGPT hilft in wenigen Fällen weil es Anregungen gibt, die aber leider sehr häufig völlig unpassend sind. Dass ich die falsche Version von test-case genommen habe - im Rückblick logisch dass test-case dieselbe Version wie das Contao haben muss - aber wenn ich halt nicht selber drauf komme, bedeutet es - da niemand hilft - tagelangen Frust. ich habe dazu einfach keine Lust mehr.

**Comment by Ernestopheles** [comment]
Habe Draft Version gepushed. Wenn - vielleicht schaffen wir das gemeinsam?? - der Integrationstest lauffähig ist, ergänze ich die anderen use cases und ich erstelle ein neues Release.

**Comment by Ernestopheles** [comment]
Bin mit viel Mühe trotz fehlender Hilfe weiter gekommen

**Comment by Ernestopheles** [comment]
Leider gibt es eine weitere Hürde, die ich bisher nicht nehmen konnte. Gelungen ist das Instanzieren eines Cart und eines Item, jedoch läuft das Produkt auf Fehler. Siehe [Forum](https://community.contao.org/de/showthread.php?85423-Isotope-getProduct()-liefert-null&p=574094#post574094)

**Comment by Ernestopheles** [comment]
ENDE; Die weitere Arbeit wäre sinnlos.

**Comment by Ernestopheles** [comment]
Aufgabe gelöst, bitte teste den Release Kandidaten.

**Comment by Ernestopheles** [comment]
v2.1.0-RC1 ready for community test
